language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mrl0co/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mrl0co/docker-react npm run test -- --coverage